// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type HookPreToolUseDecision = { "decision": "allow" } | { "decision": "deny", reason: string, } | { "decision": "modify", new_input: JsonValue, };
