// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type HookPostToolUseFailureEvent = { 
/**
 * Turn ID that this notification belongs to.
 */
turn_id: string, 
/**
 * Identifier that uniquely identifies this tool call.
 */
call_id: string, 
/**
 * Tool name that was invoked.
 */
tool_name: string, 
/**
 * Tool input payload used for execution.
 */
tool_input: JsonValue, 
/**
 * Failure message returned by execution.
 */
error: string, };
