// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type HookPreToolUseRequestEvent = { 
/**
 * Turn ID that this request belongs to.
 */
turn_id: string, 
/**
 * Identifier that uniquely identifies this hook request.
 */
call_id: string, 
/**
 * Tool name being invoked.
 */
tool_name: string, 
/**
 * Tool input payload.
 */
tool_input: JsonValue, };
